# platform = multi_platform_slmicro,multi_platform_rhel,multi_platform_fedora
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low

- name: Ensure /etc/security/opasswd exist and has the correct permissions
  ansible.builtin.file:
    path: /etc/security/opasswd
    owner: root
    group: root
    mode: 0600
    state: touch
